<?php
$currentUrl = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 
$storeId =  $storeManager->getStore()->getCode();

?>
<link rel="alternate" hreflang="<?php echo $storeId; ?>" href="<?php echo $currentUrl; ?>">